language: perl6
perl6:
  - latest
  - '2017.08'
  - '2017.07'
install:
  - rakudobrew build-zef
  - zef install --debug DBIish --/test
  - zef install --debug Bailador --/test
  - zef install --debug Crypt::Bcrypt --/test

matrix:
  allow_failures:
  - perl6: latest
