language: perl6
perl6:
  - latest
  - '2018.04'
  - '2018.01'
  - '2017.12'
  - '2017.11'
  - '2017.10'
  - '2017.09'
  - '2017.08'
  - '2017.07'
install:
  - rakudobrew build-zef
  - zef install --deps-only .

#  - zef install --debug DBIish --/test
#  - zef install --debug Net::SMTP --/test
#  - zef install --debug Email::Simple --/test
#  - zef install --debug UUID --/test
#  - zef install --debug Bailador --/test
#  - zef install --debug Crypt::Bcrypt --/test

matrix:
  allow_failures:
  - perl6: latest
